version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - clangd:/workarea/.cache
      - vscode-extensions:/root/.vscode-server/extensions
      - ..:/workarea:cached
      - ../grpc:/workarea/grpc
    command: sleep infinity

volumes:
  clangd:
  vscode-extensions: